name: auto_update_cron_job

on:
  schedule: # Runs every hour at 0 minutes
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vmSize: [2]

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - run: python -m pip install poetry
      - run: python -m poetry config virtualenvs.in-project true && python -m poetry install
      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo apt-get install -y google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
      - run: python -m poetry run python src/cyberowl/main.py
      - name: Setup git config
        run: |
          git config user.name "CyberOwl Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          git add src/cyberowl README.md docs/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Automatic update with GitHub Actions"
            git push origin ${GITHUB_REF##*/}
          fi

  deploy: # This job will only run if the previous job was successful, it will deploy the changes to the /docs folder to s3 bucket
    needs: run-and-commit
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        npm install
    - name: Build
      env:
        GA_ID: ${{ secrets.GA_ID }}
      run: |
        npm run docs:build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Copy the files from /docs/.vuepress/dist to s3 bucket
      run: |
        aws s3 sync ./docs/.vuepress/dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
